### ISSUE TITLE
What does the badge over the extension logo mean ?

### ISSUE THREAD

**Issue by rackstraw** [andreas0607/CoinHive-blocker#1]
Clicking the logo toggles it's badge between "off" and "on".  However if the badge originally says "ON",  and the logo is clicked, does that mean:

1)  CoinHiveBlocker will turn OFF, the opposite of the original value in the badge, or
2)  CoinHiveBlocker will turn ON, the same as the original value in the badge.

I studied the source but I couldn't figure it out.

**Comment by AMoldskred** [comment]
I am sorry for the inconvenience. I should have been more clear in my
description. The badge displays the state of the extension. So when it says
off, the blocker is off. When it says on, the block is on. I will soon add
a third choice that shows the statistics for the blocker. It will then be:
Off(is off), On(is on), Stats(Click to display statistics).

I hope this explains. Any other questions?

Best regards
Andreas Molle
