### ISSUE TITLE
Logging off or more detailed

### ISSUE THREAD

**Issue by tonytamps** [andreas0607/CoinHive-blocker#6]
Hey, so I had the console open and saw the message "removed items" and thought that the extension had blocked something on the site.

I checked the source and the message prints whenever the blocker is running, regardless of what it blocks:
https://github.com/andreas0607/CoinHive-blocker/blob/master/remove.js#L37

Maybe it should be more verbose? `CHB not running` `CHB running: nothing blocked` `CHB running: blocked coin-hive`?

I know you're working on stats (which I'm super keen on) so maybe some of the need for this will go away when that happens. In that case I suggest removing the random console messages.

**Comment by AMoldskred** [comment]
You're right, I'll change it right now. But I'll wait with publishing a new version until I get some real work done. Thank you  for the feedback :)

**Comment by tonytamps** [comment]
No probs, thank you dude.
